# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

name: $(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
      - master
pr: none

pool:
  name: Azure Pipelines
  vmImage: windows-latest
  demands:
  - msbuild
  - vstest

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  ProductBinPath: '$(Build.SourcesDirectory)\src\Microsoft.OpenApi\bin\$(BuildConfiguration)' 


stages:

- stage: build
  jobs:
    - job: build
      steps:
      - task: UseDotNet@2
        displayName: 'Use .NET 6'
        inputs:
          version: 6.x

      - task: PoliCheck@1
        displayName: 'Run PoliCheck "/src"'
        inputs:
          inputType: CmdLine
          cmdLineArgs: '/F:$(Build.SourcesDirectory)/src /T:9 /Sev:"1|2" /PE:2 /O:poli_result_src.xml'

      - task: PoliCheck@1
        displayName: 'Run PoliCheck "/test"'
        inputs:
          inputType: CmdLine
          cmdLineArgs: '/F:$(Build.SourcesDirectory)/test /T:9 /Sev:"1|2" /PE:2 /O:poli_result_test.xml'

      # Install the nuget tool.
      - task: NuGetToolInstaller@0
        displayName: 'Use NuGet >=5.2.0'
        inputs:
          versionSpec: '>=5.2.0'
          checkLatest: true

      # Build the Product project
      - task: DotNetCoreCLI@2
        displayName: 'build'
        inputs:
          projects: '$(Build.SourcesDirectory)\Microsoft.OpenApi.sln'
          arguments: '--configuration $(BuildConfiguration) --no-incremental'

      # Run the Unit test
      - task: DotNetCoreCLI@2
        displayName: 'test'
        inputs:
          command: test
          projects: '$(Build.SourcesDirectory)\Microsoft.OpenApi.sln'
          arguments: '--configuration $(BuildConfiguration) --no-build'

      # CredScan
      - task: securedevelopmentteam.vss-secure-development-tools.build-task-credscan.CredScan@2
        displayName: 'Run CredScan - Src'
        inputs:
          toolMajorVersion: 'V2'
          scanFolder: '$(Build.SourcesDirectory)\src'
          debugMode: false

      - task: securedevelopmentteam.vss-secure-development-tools.build-task-credscan.CredScan@2
        displayName: 'Run CredScan - Test'
        inputs:
          toolMajorVersion: 'V2'
          scanFolder: '$(Build.SourcesDirectory)\test'
          debugMode: false

      - task: AntiMalware@3
        displayName: 'Run MpCmdRun.exe - ProductBinPath'
        inputs:
          FileDirPath: '$(ProductBinPath)'
        enabled: false

      - task: BinSkim@3
        displayName: 'Run BinSkim - Product Binaries'
        inputs:
          InputType: Basic
          AnalyzeTarget: '$(ProductBinPath)\**\Microsoft.OpenApi.dll'
          AnalyzeSymPath: '$(ProductBinPath)'
          AnalyzeVerbose: true
          AnalyzeHashes: true
          AnalyzeEnvironment: true

      - task: PublishSecurityAnalysisLogs@2
        displayName: 'Publish Security Analysis Logs'
        inputs:
          ArtifactName: SecurityLogs

      - task: PostAnalysis@1
        displayName: 'Post Analysis'
        inputs:
          BinSkim: true
          CredScan: true
          PoliCheck: true

      - task: SFP.build-tasks.custom-build-task-1.EsrpCodeSigning@1
        displayName: 'ESRP CodeSigning'
        inputs:
          ConnectedServiceName: 'microsoftgraph ESRP CodeSign DLL and NuGet (AKV)'
          FolderPath: src
          signConfigType: inlineSignParams
          inlineOperation: |
            [
                {
                    "keyCode": "CP-230012",
                    "operationSetCode": "SigntoolSign",
                    "parameters": [
                    {
                        "parameterName": "OpusName",
                        "parameterValue": "Microsoft"
                    },
                    {
                        "parameterName": "OpusInfo",
                        "parameterValue": "http://www.microsoft.com"
                    },
                    {
                        "parameterName": "FileDigest",
                        "parameterValue": "/fd \"SHA256\""
                    },
                    {
                        "parameterName": "PageHash",
                        "parameterValue": "/NPH"
                    },
                    {
                        "parameterName": "TimeStamp",
                        "parameterValue": "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
                    }
                    ],
                    "toolName": "sign",
                    "toolVersion": "1.0"
                },
                {
                    "keyCode": "CP-230012",
                    "operationSetCode": "SigntoolVerify",
                    "parameters": [ ],
                    "toolName": "sign",
                    "toolVersion": "1.0"
                }
            ]
          SessionTimeout: 20
      
      # Pack
      - task: DotNetCoreCLI@2
        displayName: 'pack OpenAPI'
        inputs:
          command: pack
          projects: src/Microsoft.OpenApi/Microsoft.OpenApi.csproj
          arguments: '-o $(Build.ArtifactStagingDirectory)/Nugets --configuration $(BuildConfiguration) --no-build --include-symbols --include-source /p:SymbolPackageFormat=snupkg'
      
      # Pack
      - task: DotNetCoreCLI@2
        displayName: 'pack Readers'
        inputs:
          command: pack
          projects: src/Microsoft.OpenApi.Readers/Microsoft.OpenApi.Readers.csproj
          arguments: '-o $(Build.ArtifactStagingDirectory)/Nugets --configuration $(BuildConfiguration) --no-build --include-symbols --include-source /p:SymbolPackageFormat=snupkg'
      
      # Pack
      - task: DotNetCoreCLI@2
        displayName: 'pack Hidi'
        inputs:
          command: pack
          projects: src/Microsoft.OpenApi.Hidi/Microsoft.OpenApi.Hidi.csproj
          arguments: '-o $(Build.ArtifactStagingDirectory)/Nugets --configuration $(BuildConfiguration) --no-build --include-symbols --include-source /p:SymbolPackageFormat=snupkg'
      
      - task: SFP.build-tasks.custom-build-task-1.EsrpCodeSigning@1
        displayName: 'ESRP CodeSigning Nuget Packages'
        inputs:
          ConnectedServiceName: 'microsoftgraph ESRP CodeSign DLL and NuGet (AKV)'
          FolderPath: '$(Build.ArtifactStagingDirectory)'
          Pattern: '*.nupkg'
          signConfigType: inlineSignParams
          inlineOperation: |
            [
                {
                    "keyCode": "CP-401405",
                    "operationSetCode": "NuGetSign",
                    "parameters": [ ],
                    "toolName": "sign",
                    "toolVersion": "1.0"
                },
                {
                    "keyCode": "CP-401405",
                    "operationSetCode": "NuGetVerify",
                    "parameters": [ ],
                    "toolName": "sign",
                    "toolVersion": "1.0"
                }
            ]
          SessionTimeout: 20

      - task: PowerShell@2
        displayName: "Get Hidi's version-number from .csproj"
        inputs:
          targetType: 'inline'
          script: |
              $xml = [Xml] (Get-Content .\src\Microsoft.OpenApi.Hidi\Microsoft.OpenApi.Hidi.csproj)
              $version = $xml.Project.PropertyGroup.Version
              echo $version
              echo "##vso[task.setvariable variable=version]$version"  

      # publish hidi as an .exe
      - task: DotNetCoreCLI@2
        inputs:
          command: 'publish'
          arguments: -c Release --runtime win-x64 /p:PublishSingleFile=true --self-contained --output $(Build.ArtifactStagingDirectory)/Microsoft.OpenApi.Hidi-v$(version) --no-dependencies
          projects: 'src/Microsoft.OpenApi.Hidi/Microsoft.OpenApi.Hidi.csproj'
          publishWebProjects: False
          zipAfterPublish: false 

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact: Hidi'
        inputs: 
          ArtifactName: Microsoft.OpenApi.Hidi-v$(version)
          PathtoPublish: '$(Build.ArtifactStagingDirectory)/Microsoft.OpenApi.Hidi-v$(version)'

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact: Nugets'
        inputs:
          ArtifactName: Nugets
          PathtoPublish: '$(Build.ArtifactStagingDirectory)/Nugets'

- stage: deploy
  condition: and(contains(variables['build.sourceBranch'], 'refs/heads/vnext'), succeeded())
  dependsOn: build
  jobs:
    - deployment: deploy
      environment: nuget-org
      strategy:
        runOnce:
          deploy:
            pool:
              vmImage: ubuntu-latest
            steps:
            - task: DownloadPipelineArtifact@2
              displayName: Download nupkg from artifacts
              inputs:
                artifact: Nugets
                source: current
            - task: NuGetCommand@2
              displayName: 'NuGet push'
              inputs:
                command: push
                packagesToPush: '$(Pipeline.Workspace)/Nugets/Microsoft.OpenApi.*.nupkg'
                nuGetFeedType: external
                publishFeedCredentials: 'OpenAPI Nuget Connection'
